### ISSUE TITLE
A coding exception was thrown in a Promise resolution callback.

### ISSUE THREAD

**Issue by Bijman** [freaktechnik/twitch-provider#15] opened 2016-01-09 22:19 UTC
Hello.

Here is an issue. 
I'm using up to date Arch Linux box with latest Instantbird build ver. 1.6a1pre (20151227041434) from http://ftp.instantbird.org/instantbird and created Twitch Provider xpi package using jpm. 
Then I opened Instantbird and installed addon. After that I successfully added my Twitch account and joined chat. Everything worked fine, but when I close Instantbird and open again, I can't login to Twitch. Also this appears in error console:

>Error: A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise
Date: Sat Jan 09 2016 23:09:21 GMT+0100 (CET)
Full Message: TypeError: target is null
Full Stack: create@resource://gre/modules/commonjs/sdk/frame/utils.js:52:7
@resource://gre/modules/commonjs/sdk/addon/window.js:32:13
startup/<@resource://gre/modules/commonjs/sdk/addon/runner.js:72:21
Handler.prototype.process@resource://gre/modules/Promise-backend.js:933:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:812:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise-backend.js:746:1
promise callback*this.PromiseWalker.scheduleWalkerLoop@resource://gre/modules/Promise-backend.js:745:9
this.PromiseWalker.schedulePromise@resource://gre/modules/Promise-backend.js:775:7
this.PromiseWalker.completePromise@resource://gre/modules/Promise-backend.js:710:7
listener/<@resource://gre/modules/sdk/system/Startup.js:51:46
Source File: resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/frame/utils.js
Line: 52
Source Code:
52

And when I open Accounts, I got this:
![przechwycenie obrazu ekranu_2016-01-09_20-20-55](https://cloud.githubusercontent.com/assets/16626326/12217880/cab703d2-b70e-11e5-9243-12240dedaed1.png)

This issue happens too, if I change to other nightly 1.6a1pre build and new .instantbird directory at my home folder.

**Comment by freaktechnik** [comment] 2016-01-09 22:37
This is essentially a duplicate of #2 and is actually part of #10 - sorry. Solution is to disable and re-enable the add-on until I've got this fixed in Instantbird. Note that with a normal Instantbird you will also have to re-add the account every time you start Instantbird and re-enabled the extension. See #10 for details on stuff that needs to happen in instantbird for this extension to work properly. Only stuff that's checked off is fixed in Instantbird nightlies.

**Closed** 2016-01-09 22:37 UTC
Labels: duplicate
